### ISSUE TITLE
license

### ISSUE THREAD

**Issue by mrzl** [neilmendoza/ofxPostProcessing#19]
hey, thanks for this addon. I'm wondering what kind of license you're publishing this in...? I've been using it tons of times and would like to once know for sure what your opinion about this is..

thanks already :)

yours,
marcel

**Comment by mactkg** [comment]
@mrzl BSD?

https://github.com/neilmendoza/ofxPostProcessing/blob/master/src/ofxPostProcessing.h#L7-L29

**Comment by mrzl** [comment]
oh yeh. cheers.
