### ISSUE TITLE
Won't compile in 0.9.8

### ISSUE THREAD

**Issue by microcosm** [neilmendoza/ofxPostProcessing#23]
[This commit](https://github.com/neilmendoza/ofxPostProcessing/commit/3c2779b0290b6a9f4b80d1eb995e2b1d7b3e3181) uses ofFboBeginMode, an enum which isn't introduced in the latest OF public versioned release. That means end users have to be working off the development branch, and many newcomers to OF will download your addon only to find it doesn't compile.

I just thought I should point that out, I'm not sure what you could do about it. Maybe put the dev version stuff in a dev branch, or add a note to the readme that this addon is for advanced users only..?

**Comment by neilmendoza** [comment]
Yes, the addon follows the same branch setup as OF, master is the dev branch and stable is the release branch. Will add a note to the readme. Thanks!
