### ISSUE TITLE
 Error or: raw.begin(ofFboBeginMode::NoDefaults);

### ISSUE THREAD

**Issue by cyrstem** [neilmendoza/ofxPostProcessing#25]
trying to compile  i get this  Use of undeclared identifier 'ofFboBeginMode'

**Comment by neilmendoza** [comment]
From the readme:

NB This addon uses the branch setup as OF itself, the stable branch corresponds to the most recent release (i.e. the version that is downloadable from the OF site) and the master branch is the develop branch. If you have downloaded from the website, the you will want to use the stable branch...

https://github.com/neilmendoza/ofxPostProcessing/tree/stable
